package az.fitnest.payment.client.abb.bnpl;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * ABB BNPL (Buy Now Pay Later) External API configuration.
 *
 * <p>Separate from Azericard {@code abb:} installment gateway — OAuth2 + REST.</p>
 */
@Data
@Component
@ConfigurationProperties(prefix = "abb-bnpl")
public class AbbBnplProperties {

    /**
     * OAuth2 token endpoint.
     * Test: https://test-id.abb-bank.az/realms/partner/protocol/openid-connect/token
     * Prod: https://id.abb-bank.az/realms/abb-partners/protocol/openid-connect/token
     */
    private String authUrl =
            "https://test-id.abb-bank.az/realms/partner/protocol/openid-connect/token";

    /**
     * BNPL API base URL (without trailing slash).
     * Test: https://api-test.abb-bank.az
     * Prod: https://api.abb-bank.az
     */
    private String apiBaseUrl = "https://api-test.abb-bank.az";

    /** OAuth2 client_id registered with ABB. */
    private String clientId;

    /**
     * RSA private key (PKCS#8 or PKCS#1 PEM / Base64) used to sign client_assertion JWT (RS256).
     */
    private String privateKey;

    /**
     * Optional audience override for client_assertion JWT.
     * Defaults to {@link #authUrl} when blank.
     */
    private String tokenAudience;

    /** OAuth scope. Doc default: openid */
    private String scope = "openid";

    /** HTTP connect/read timeout for ABB API calls (ms). */
    private long timeoutMs = 10000;

    /**
     * Callback Basic Auth credentials that ABB will send to FitNest.
     * Generated by FitNest and registered with ABB during onboarding.
     */
    private String callbackUsername;
    private String callbackPassword;

    /**
     * Optional HMAC secret for X-Signature verification.
     * Algorithm details pending ABB clarification — when blank, signature check is skipped.
     */
    private String callbackHmacSecret;

    /** Supported credit terms shown to mobile (ABB may still reject unavailable ones). */
    private List<Integer> activeTerms = List.of(1, 3, 4, 6, 9, 12, 18, 24);

    /**
     * When true, public BNPL endpoints return maintenance / NOT_FOUND.
     * Keep true until ABB onboarding credentials are ready.
     */
    private boolean maintenanceMode = true;

    /** Default product name prefix when package name is unavailable. */
    private String defaultProductName = "FitNest Abunəlik";
}
