package az.fitnest.payment.util;

import java.util.HashMap;
import java.util.Map;

public class EpointBankResponseCodes {
    private static final Map<String, String> codeToMessage = new HashMap<>();
    static {
        codeToMessage.put("000", "Təsdiq edildi");
        codeToMessage.put("100", "İmtina (ümumi, şərh yoxdur)");
        codeToMessage.put("101", "İmtina (kartın istifadə müddəti bitib)");
        codeToMessage.put("102", "İmtina (fırıldaqçılığdan şübhə)");
        codeToMessage.put("103", "İmtina (qəbul edən ekvayer bank ilə əlaqə saxlasın)");
        codeToMessage.put("104", "İmtina (məhdudlaşdırılmış kart)");
        codeToMessage.put("105", "İmtina (qəbul edən ekvayer bankın təhlükəsizlik şöbəsi ilə əlaqə saxlasın)");
        codeToMessage.put("106", "İmtina (icazə verilən PIN cəhtləri keçildi)");
        codeToMessage.put("107", "İmtina (kart emitentinə müraciət edin)");
        codeToMessage.put("108", "İmtina (kart emitentinin xüsusi şərtlərinə müraciət edin)");
        codeToMessage.put("109", "İmtina, etibarsız tacir");
        codeToMessage.put("110", "İmtina, etibarsız məbləğ");
        codeToMessage.put("111", "İmtina, etibarsız kart nömrəsi");
        codeToMessage.put("112", "İmtina, PIN tələb olunur");
        codeToMessage.put("113", "İmtina, qəbuledilməz məbləğ");
        codeToMessage.put("114", "İmtina, tələb edilən hesab növü yoxdur");
        codeToMessage.put("115", "İmtina, tələb edilən funksiya dəstəklənmir");
        codeToMessage.put("116", "İmtina, kifayət qədər vəsait yoxdur");
        codeToMessage.put("117", "İmtina, səhv PIN");
        codeToMessage.put("118", "İmtina, kart məlumatları yoxdur");
        codeToMessage.put("119", "İmtina, kart sahibinə əməliyyat üçün icazə verilmir");
        codeToMessage.put("120", "İmtina, terminala əməliyyat üçün icazə verilmir");
        codeToMessage.put("121", "İmtina, pul çıxarma limiti keçib");
        codeToMessage.put("122", "İmtina, təhlükəsizlik pozuntusu");
        codeToMessage.put("123", "İmtina, vəsaitlərin çıxarılması tezliyinin limiti aşılıb");
        codeToMessage.put("124", "İmtina, qanun pozuntusu");
        codeToMessage.put("125", "İmtina, etibarsız kart");
        codeToMessage.put("126", "İmtina, PIN bloku səhvdir");
        codeToMessage.put("127", "İmtina, PIN uzunluğu xətası");
        codeToMessage.put("128", "İmtina, PIN sinxronizasıya xətası");
        codeToMessage.put("129", "İmtina, saxta kartdan şübhələnilir");
        codeToMessage.put("180", "İmtina, kart sahibinin istəyi ilə");
        codeToMessage.put("200", "Pick-up (ümumi, şərhsiz)");
        codeToMessage.put("201", "Pick-up (kartın istifadə müddəti bitib)");
        codeToMessage.put("202", "Pick-up (dələduzluqdan şübhə)");
        codeToMessage.put("203", "Pick-up, qəbul edən bank ekvayer ilə əlaqə saxlasın");
        codeToMessage.put("204", "Pick-up, məhdudlaşdırılmış kart");
        codeToMessage.put("205", "Pick-up (qəbul edən ekvayer bankın təhlükəsizlik şöbəsi ilə əlaqə saxlasın)");
        codeToMessage.put("206", "Pick-up (icazə verilən PIN cəhtləri keçildi)");
        codeToMessage.put("207", "Pick-up, xüsusi şərait");
        codeToMessage.put("208", "Pick-up, itirilmiş kart");
        codeToMessage.put("209", "Pick-up, oğurlanmış kart");
        codeToMessage.put("210", "Pick-up, saxta kartdan şübhələnilir");
        codeToMessage.put("300", "Status mesajı: fayl əməliyyatı uğurludur");
        codeToMessage.put("301", "Status mesajı: fayl əməliyyatı qəbuledici tərəfindən dəstəklənmir");
        codeToMessage.put("302", "Status mesajı: faylda qeydi tapmaq mümkün deyil");
        codeToMessage.put("303", "Status mesajı: dublikat qeyd, köhnə qeyd dəyişdirildi");
        codeToMessage.put("304", "Status mesajı: fayl qeydi sahəsində redaktə xətası");
        codeToMessage.put("305", "Status mesajı: fayl kilidlənib");
        codeToMessage.put("306", "Status mesajı: fayl əməliyyatı uğursuzdur");
        codeToMessage.put("307", "Status mesajı: fayl məlumat formatı xətası");
        codeToMessage.put("308", "Status mesajı: dublikat qeyd, yeni qeyd rədd edildi");
        codeToMessage.put("309", "Status mesajı: naməlum fayl");
        codeToMessage.put("400", "Qəbul edildi (qaytarma üçün)");
        codeToMessage.put("499", "Təsdiq edildi, orijinal mesaj datası yoxdur");
        codeToMessage.put("500", "Status mesajı: tutuşdurulub, balansdadır");
        codeToMessage.put("501", "Status mesajı: tutuşdurulub, balansda deyil");
        codeToMessage.put("502", "Status mesajı: məbləğ tutuşdurulmayıb, cəmi təmin edilib");
        codeToMessage.put("503", "Status mesajı: tutuşdurulmaq üçün cəmlər mövcud deyil");
        codeToMessage.put("504", "Status mesajı: tutuşdurulmayıb, cəmi təmin edilib");
        codeToMessage.put("600", "Qəbul edildi (administrativ məlumat üçün)");
        codeToMessage.put("601", "Status mesajı: həqiqi əməliyyatı izləmək mümkün deyil");
        codeToMessage.put("602", "Status mesajı: əməliyyat üçün yanlış istinad nömrəsi");
        codeToMessage.put("603", "Status mesajı: istinad nömrəsi / PAN uyğunsuzdur");
        codeToMessage.put("604", "Status mesajı: POS fotoşəkili mövcud deyil");
        codeToMessage.put("605", "Status mesajı: tələb olunan element təqdim edildi");
        codeToMessage.put("606", "Status mesajı: sorğu icra edilə bilməz - tələb olunan sənədlər mövcud deyil");
        codeToMessage.put("680", "Siyahı hazırdır");
        codeToMessage.put("681", "Siyahı hazır deyil");
        codeToMessage.put("700", "Qəbul edildi (ödəniş toplamaq üçün)");
        codeToMessage.put("800", "Qəbul edildi (şəbəkəyə nəzarət üçün)");
        codeToMessage.put("900", "Tövsiyə nəzərə alındı, heç bir maliyyə öhdəliyi qəbul edilmədi");
        codeToMessage.put("901", "Tövsiyələr nəzərə alındı, maliyyə öhdəliyi qəbul edildi");
        codeToMessage.put("902", "İmtina səbəbi ismarıcı: etibarsız əməliyyat");
        codeToMessage.put("903", "Status ismarıcı: əməliyyatın yenidən daxil edilməsi");
        codeToMessage.put("904", "İmtina səbəbi ismarıcı: format səhvi");
        codeToMessage.put("905", "İmtina səbəbi ismarıcı: ekvayer kommutator tərəfindən dəstəklənmir");
        codeToMessage.put("906", "İmtina səbəbi ismarıcı: azalma prosesində");
        codeToMessage.put("907", "İmtina səbəbi ismarıcı: kart emitenti və ya keçid işləmir");
        codeToMessage.put("908", "İmtina səbəbi ismarıcı: marşrutlaşdırma üçün əməliyyat təyinat yerini tapa bilmir");
        codeToMessage.put("909", "İmtina səbəbi ismarıcı: sistem nasazlığı");
        codeToMessage.put("910", "İmtina səbəbi ismarıcı: kart emitenti söndürüldü");
        codeToMessage.put("911", "İmtina səbəbi ismarıcı: kartın emitentinin gözləmə müddəti bitmişdir");
        codeToMessage.put("912", "İmtina səbəbi ismarıcı: kartın emitenti mövcud deyil");
        codeToMessage.put("913", "İmtina səbəbi: dublikat ötürmə");
        codeToMessage.put("914", "İmtina səbəbi: tranzaksiyaları izləmək mümkün deyil");
        codeToMessage.put("915", "İmtina səbəbi: uyğunlaşdırma və ya nəzarət nöqtəsinin sönmə səhvi");
        codeToMessage.put("916", "İmtina səbəbi: Yanlış MAC");
        codeToMessage.put("917", "İmtina səbəbi: MAC açarının yanlış sinxronizasiyası");
        codeToMessage.put("918", "İmtina səbəbi: istifadə üçün bağlayıcı açarların mövcudsuzluğu");
        codeToMessage.put("919", "İmtina səbəbi: şifrələnmə açarı sinxronlaşması səhvi");
        codeToMessage.put("920", "İmtina səbəbi: proqram/donanım təhlükəsizliyi səhvi - bir daha sınayın");
        codeToMessage.put("921", "İmtina səbəbi: proqram/donanım təhlükəsizliyi səhvi - fəaliyyət yoxdur");
        codeToMessage.put("922", "İmtina səbəbi: ismaric nömrəsinin ardıcılılığının pozulması");
        codeToMessage.put("923", "Status ismarici: müraciət prosesdədir");
        codeToMessage.put("950", "İmtina səbəbi: iş razılaşmasının pozuntusu");
        codeToMessage.put("0Y1", "Təsdiqləndi, ICC oflayn rejimində");
        codeToMessage.put("0Y3", "Təsdiqləndi, ICC oflayn rejimində");
        codeToMessage.put("1Q1", "İmtina, ICC oflayn rejimi səbəbindən");
        codeToMessage.put("1Z1", "İmtina, ICC oflayn rejimi səbəbindən");
        codeToMessage.put("1Z3", "İmtina, ICC oflayn rejimi səbəbindən");
    }

    public static String getMessage(String code) {
        return codeToMessage.getOrDefault(code, "Naməlum xəta baş verdi");
    }
}
